PROTECTED_VALUES = [
    "BLUE-4821"
]
def validate_output(response):
    for secret in PROTECTED_VALUES:

        # Check original secret
        if secret.lower() in response.lower():
            return "DENIED - Protected information detected"

        # Check reversed secret
        reversed_secret = secret[::-1]

        if reversed_secret.lower() in response.lower():
            return "DENIED - Transformed protected information detected"

    return response
# Simulate output generated by the LLM
llm_response = input("Enter LLM response: ")

result = validate_output(llm_response)

print("\nFinal output:")
print(result)