# Attack 08 – Improper Output Handling

## Objective

This lab demonstrates the risk of improperly trusting LLM-generated output before passing it to downstream application components.

The goal was to simulate an application that accepts SQL generated by an LLM, demonstrate how unsafe output could reach a downstream database handler, implement validation controls, test a bypass against the initial mitigation, and strengthen the control using an allowlist approach.

No real database was connected during this lab. All database execution was simulated.

---

## Vulnerable Output Handling

A simulated LLM generated two SQL statements:

- A legitimate read-only query
- A destructive `DROP TABLE` query

The vulnerable application passed both outputs directly to the simulated database handler without validation.

This demonstrated the danger of treating LLM-generated output as trusted application input.

![Unvalidated Output Execution](01-unvalidated-output-execution.png)

---

## Basic Output Validation

A Python validation layer was added between the LLM output and the simulated database handler.

The initial validator:

- Required output to begin with `SELECT`
- Blocked several known destructive SQL keywords
- Allowed output only after validation

The legitimate `SELECT` query was allowed.

The `DROP TABLE` query was successfully denied.

![SQL Output Validation](02-sql-output-validation.png)

---

## Basic Validator Bypass

The initial mitigation was then tested against a more complex output:

`SELECT name FROM research_projects; EXEC dangerous_procedure;`

The statement began with `SELECT`, satisfying the initial allow condition.

The validator also did not include `EXEC` in its blocked keyword list.

As a result, the output passed validation even though it contained an additional unapproved operation.

This demonstrated a weakness in relying on simple keyword denylisting.

![Basic Validator Bypass](03-basic-validator-bypass.png)

---

## Strict Allowlist Validation

A stronger validation strategy was implemented.

Instead of attempting to identify every possible dangerous SQL keyword, the application defined the specific SQL structure it was designed to accept.

The approved structure was:

`SELECT <column> FROM research_projects;`

Outputs were required to match the entire approved structure.

The results were:

- Legitimate `SELECT` query → ALLOWED
- `DROP TABLE` query → DENIED
- Multi-statement `SELECT ...; EXEC ...` output → DENIED

![Strict Allowlist Validation](04-strict-allowlist-validation.png)

---

## Legitimate Structure Retest

The legitimate query was changed from:

`SELECT name FROM research_projects;`

to:

`SELECT status FROM research_projects;`

The new query was still allowed because it followed the approved SQL structure.

The destructive and multi-statement outputs remained denied.

This demonstrated that the allowlist enforced an approved output structure without requiring one exact hard-coded query.

![Legitimate Structure Retest](05-legitimate-structure-retest.png)

---

## Implementation

The lab contains three Python programs.

### `vulnerable_output_handler.py`

Demonstrates an application passing LLM-generated SQL directly to a simulated downstream database handler without validation.

### `secure_output_handler.py`

Introduces basic validation using a required `SELECT` prefix and a denylist of destructive SQL keywords.

This mitigation blocks obvious destructive output but can be bypassed by unexpected operations not included in the denylist.

### `strict_output_handler.py`

Implements a stricter allowlist-based validation strategy.

Only output matching the application's approved SQL structure is accepted.

---

## Security Controls Demonstrated

This lab demonstrates:

- Treating LLM output as untrusted input
- Application-layer output validation
- Separating LLM generation from downstream execution
- Testing mitigations for bypasses
- Denylist versus allowlist validation
- Strict output structure enforcement
- Legitimate-functionality retesting

---

## Key Finding

LLM-generated output should not automatically be trusted simply because it appears valid or begins with an expected command.

The initial keyword-based validator successfully blocked an obvious destructive query but failed when an unexpected operation was appended to an otherwise legitimate-looking statement.

A stricter allowlist reduced this risk by defining what the application was permitted to accept rather than attempting to identify every possible unsafe output.

The application, not the LLM, should enforce the security boundary before model-generated output reaches downstream systems.

---

## Production Considerations

The validation used in this lab is a simplified demonstration.

A production application should avoid giving an LLM unrestricted control over database queries. Additional protections may include:

- Parameterized queries
- Read-only database identities
- Least-privilege permissions
- Constrained application functions or APIs
- Structured output schemas
- Logging and monitoring
- Human approval for high-impact operations

---

## OWASP Mapping

This lab was developed while studying:

**OWASP Top 10 for LLM Applications 2026 – LLM10: Improper Output Handling**

The exercise demonstrates the risk of insufficient validation of LLM-generated output before that output is passed to downstream application components.