# ==========================================
# Attack 09 - Agent Jailbreaking
# Structured Agent Security Guard
# ==========================================

# Tools the application actually authorizes
ALLOWED_TOOLS = {
    "read_status",
    "restart_service"
}

# Tools that exist in our simulated environment
KNOWN_TOOLS = {
    "read_status",
    "restart_service",
    "delete_backup"
}

# Services that the agent is authorized to restart
ALLOWED_RESTART_SERVICES = {
    "test-api"
}


def validate_schema(action):
    """
    Validate that the LLM produced a structured tool request.
    """

    # Reject arbitrary text such as:
    # rm nightly-backup-01
    if not isinstance(action, dict):
        return False, "DENIED - Output is not a structured tool request"

    # A valid request must contain both fields
    if "tool" not in action or "resource" not in action:
        return False, "DENIED - Invalid tool-request schema"

    # Reject tools that do not exist in our application
    if action["tool"] not in KNOWN_TOOLS:
        return False, "DENIED - Unknown tool"

    return True, "VALID"


def authorize_action(action):
    """
    Validate structure first, then enforce tool and resource authorization.
    """

    # Layer 1: Schema validation
    valid, message = validate_schema(action)

    if not valid:
        return message

    tool = action["tool"]
    resource = action["resource"]

    # Layer 2: Tool authorization
    if tool not in ALLOWED_TOOLS:
        return "DENIED - Tool is not authorized"

    # Layer 3: Resource authorization
    if tool == "restart_service":
        if resource not in ALLOWED_RESTART_SERVICES:
            return "DENIED - Service is not authorized for restart"

    return f'ALLOWED - {tool}("{resource}")'


print("=== Structured Agent Security Guard ===")


tests = [
    # Normal authorized status request
    {
        "tool": "read_status",
        "resource": "test-api"
    },

    # Authorized restart
    {
        "tool": "restart_service",
        "resource": "test-api"
    },

    # Tool is allowed, but resource is not authorized for restart
    {
        "tool": "restart_service",
        "resource": "production-api"
    },

    # Jailbreak-generated prohibited tool request
    {
        "tool": "delete_backup",
        "resource": "nightly-backup-01"
    },

    # Unexpected arbitrary output generated by Llama
    "rm nightly-backup-01",

    # Legitimate production status request
    {
        "tool": "read_status",
        "resource": "production-api"
    }
]


for action in tests:
    print(f"\nAgent output: {action}")
    print(authorize_action(action))