ALLOWED_TOOLS = [
    "read_document",
    "send_email"
]

ALLOWED_TOOLS = [
    "read_document",
    "send_email"
]

AUTHORIZED_EMAILS = [
    "research-team@ecu.edu",
    "security-team@ecu.edu"
]

SENSITIVE_TERMS = [
    "password",
    "secret",
    "account number",
    "social security number"
]


def authorize_tool(tool_name, recipient=None, message=None):

    # Layer 1: Check whether the requested tool is authorized
    if tool_name not in ALLOWED_TOOLS:
        return "DENIED - Unauthorized tool"

    # Additional security checks for the email tool
    if tool_name == "send_email":

        # Layer 2: Check whether the destination is authorized
        if recipient not in AUTHORIZED_EMAILS:
            return "DENIED - Unauthorized recipient"

        # Layer 3: Check whether the message contains sensitive information
        for term in SENSITIVE_TERMS:
            if term.lower() in message.lower():
                return "DENIED - Sensitive information detected"

    return "ALLOWED"


# Simulate a tool request generated by the LLM
tool_request = input("Enter requested tool: ")

recipient = None
message = None

if tool_request == "send_email":
    recipient = input("Enter email recipient: ")
    message = input("Enter message: ")

result = authorize_tool(tool_request, recipient, message)

print("\nAuthorization result:")
print(result)